# Default values for riley Helm chart

backend:
  image:
    repository: awaistahseen009/riley-backend
    tag: latest
  replicas: 2
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

frontend:
  image:
    repository: awaistahseen009/riley-frontend
    tag: latest
  replicas: 2
  apiUrl: "https://api.reporider.live/api"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

worker:
  replicas: 3
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

postgresql:
  storage: 10Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

redis:
  storage: 2Gi
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

chromadb:
  storage: 5Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

ingress:
  frontendHost: reporider.live
  backendHost: api.reporider.live
  tlsSecret: riley-tls
  clusterIssuer: letsencrypt-prod